// AN ENUM FOR STATUS CODES
export enum STATUS_CODES{
    "NOT_FOUND" = 404,
    "BAD_REQUEST" = 400,
    "SUCCESS" = 200,
    "INTERNAL_SERVER_ERROR" = 500,
    "UNAUTHORIZED" = 401,
    "CREATED" = 201,
    "FORBIDDEN" = 403,
}

// AN ENUM FOR THE USERCONTEXTREDUCERACTION TYPE
export enum USER_CONTEXT_REDUCER_ACTION_TYPE{
    "SET_USER" = "SET_USER",
    "DELETE_USER" = "DELETE_USER",
    "GET_USER" = "GET_USER"
}