import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ContextProvider from "@/components/ContextProvider"
import Navbar from "@/components/Navbar"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-3xl mx-auto p-4`}>
        <ContextProvider>
          <Navbar />
          <main>{children}</main>
        </ContextProvider>
      </body>
    </html>
  );
}
